"""End-to-end: upload -> process -> tutor -> quiz -> mastery -> growth -> recommendation -> analytics."""

from app.core import db as dbm


def test_material_processing_creates_knowledge(client, auth, ready_project):
    pid = ready_project["project"]["id"]
    material = ready_project["material"]
    assert material["page_count"] == 3
    assert material["chunk_count"] >= 1
    assert material["job"]["status"] == "completed"
    assert dbm.get_db()[dbm.CHUNKS].count_documents({"project_id": pid}) == material["chunk_count"]
    assert dbm.get_db()[dbm.CONCEPTS].count_documents({"project_id": pid}) == 3
    assert dbm.get_db()[dbm.MASTERY].count_documents({"project_id": pid}) == 3
    dash = client.get(f"/projects/{pid}", headers=auth).json()
    assert dash["progress"]["concepts_total"] == 3
    assert dash["recommendation"] is not None  # generated by MATERIAL_PROCESSED workflow
    types = {e["event_type"] for e in dash["recent_activity"]}
    assert "material_uploaded" in types and "material_processed" in types


def test_duplicate_upload_rejected(client, auth, ready_project, tmp_path):
    pdf = tmp_path / "photo.pdf"  # same bytes as the fixture upload
    with pdf.open("rb") as fh:
        r = client.post(f"/projects/{ready_project['project']['id']}/materials", files={"file": ("again.pdf", fh, "application/pdf")}, headers=auth)
    assert r.status_code == 409


def test_non_pdf_rejected(client, auth, project):
    r = client.post(f"/projects/{project['project']['id']}/materials", files={"file": ("x.pdf", b"not a pdf", "application/pdf")}, headers=auth)
    assert r.status_code == 422


def test_tutor_grounded_and_unsupported(client, auth, ready_project, fresh_db):
    pid = ready_project["project"]["id"]
    r = client.post(f"/projects/{pid}/tutor/ask/sync", json={"message": "What is photosynthesis and what does chlorophyll do?"}, headers=auth)
    assert r.status_code == 200, r.text
    data = r.json()
    assert data["type"] == "done"
    assert data["grounded"] is True
    assert data["citations"] and data["citations"][0]["page"] >= 1
    assert "[S1]" in data["message"]["content"]
    conv_id = data["message"]["conversation_id"]

    r2 = client.post(f"/projects/{pid}/tutor/ask/sync", json={"message": "zebra quantum banjo lottery tickets for tonight please", "conversation_id": conv_id}, headers=auth)
    d2 = r2.json()
    assert d2["grounded"] is False
    assert "can't find this in your materials" in d2["message"]["content"]

    conv = client.get(f"/projects/{pid}/tutor/conversations/{conv_id}", headers=auth).json()
    assert len(conv["messages"]) == 4
    # AI usage recorded with retrieval trace
    reqs = list(dbm.get_db()[dbm.AI_REQUESTS].find({"feature": "tutor"}))
    assert len(reqs) == 2 and reqs[0]["retrieval"]["hits"]
    # learner-context distillation ran for the grounded exchange
    assert dbm.get_db()[dbm.LEARNER_NOTES].count_documents({"project_id": pid, "kind": "preference"}) == 1


def test_tutor_tool_call_is_validated_and_logged(client, auth, ready_project):
    pid = ready_project["project"]["id"]
    r = client.post(f"/projects/{pid}/tutor/ask/sync", json={"message": "How am I doing so far?"}, headers=auth)
    data = r.json()
    assert data["type"] == "done"
    tool_calls = data["message"]["tool_calls"]
    assert tool_calls and tool_calls[0]["name"] == "get_learning_state" and tool_calls[0]["status"] == "ok"


def test_tutor_streaming_endpoint(client, auth, ready_project):
    pid = ready_project["project"]["id"]
    with client.stream("POST", f"/projects/{pid}/tutor/ask", json={"message": "Explain the Calvin cycle"}, headers=auth) as r:
        body = "".join(r.iter_text())
    assert "event: meta" in body and "event: delta" in body and "event: done" in body


def test_quiz_adaptive_loop_updates_mastery_and_recommends(client, auth, ready_project):
    pid = ready_project["project"]["id"]
    r = client.post(f"/projects/{pid}/quiz/sessions", json={"question_count": 3}, headers=auth)
    assert r.status_code == 201, r.text
    session = r.json()["session"]
    q = r.json()["question"]
    assert q["kind"] == "mcq" and len(q["options"]) == 4 and "correct_option" not in q
    sid = session["id"]

    # answer wrong
    wrong = 1
    a1 = client.post(f"/projects/{pid}/quiz/sessions/{sid}/answer", json={"question_id": q["id"], "answer": str(wrong)}, headers=auth).json()
    assert a1["is_correct"] is False and a1["correct_option"] == 0 and "Not quite" in a1["feedback"]
    assert a1["mastery"]["score"] < 0.3 and a1["mastery"]["attempts"] == 1
    # answering twice is rejected
    dup = client.post(f"/projects/{pid}/quiz/sessions/{sid}/answer", json={"question_id": q["id"], "answer": "0"}, headers=auth)
    assert dup.status_code == 409

    q2 = a1["next_question"]
    assert q2 is not None and q2["ordinal"] == 1
    a2 = client.post(f"/projects/{pid}/quiz/sessions/{sid}/answer", json={"question_id": q2["id"], "answer": "0" if q2["kind"] == "mcq" else "It happens in the stroma and makes glucose."}, headers=auth).json()
    assert a2["is_correct"] is True

    q3 = a2["next_question"]
    assert q3 is not None
    assert q3["kind"] == "open"  # at least one open question per quiz (ordinal 2 of 3)
    a3 = client.post(f"/projects/{pid}/quiz/sessions/{sid}/answer", json={"question_id": q3["id"], "answer": "It is in the stroma and produces glucose."}, headers=auth).json()
    assert a3["completed"] is True and a3["session"]["status"] == "completed"
    assert a3["evaluation"]["covered_points"] == ["stroma"] and a3["feedback"]
    assert a3["next_question"] is None

    # growth + recommendation (post_quiz workflow ran inline)
    growth = client.get(f"/projects/{pid}/growth", headers=auth).json()
    assert growth["overall_mastery"] > 0
    assert len(growth["history"]) == 3
    assert growth["recommendation"]["trigger"] == "quiz_completed"
    recs = client.get(f"/projects/{pid}/recommendations", headers=auth).json()
    assert recs[0]["status"] == "active" and any(r["status"] == "superseded" for r in recs)

    dash = client.get(f"/projects/{pid}", headers=auth).json()
    assert dash["progress"]["concepts_assessed"] >= 1
    assert dash["continue_learning"]["tab"] in ("growth", "quiz")

    analytics = client.get(f"/projects/{pid}/analytics", headers=auth).json()
    assert analytics["activity"]["questions_answered"] == 3
    assert analytics["performance"]["quiz_accuracy"] is not None
    assert analytics["ai_activity"]["quiz_questions_generated"] >= 3

    g = client.get("/analytics", headers=auth).json()
    assert g["overall"]["projects"] == 1 and g["performance"]["average_assessment"] is not None
    home = client.get("/home", headers=auth).json()
    assert home["continue_learning"]["project"]["id"] == pid


def test_quiz_requires_ready_material(client, auth, project):
    r = client.post(f"/projects/{project['project']['id']}/quiz/sessions", json={}, headers=auth)
    assert r.status_code == 409


def test_quiz_idempotent_start(client, auth, ready_project):
    pid = ready_project["project"]["id"]
    a = client.post(f"/projects/{pid}/quiz/sessions", json={"idempotency_key": "k1"}, headers=auth).json()
    b = client.post(f"/projects/{pid}/quiz/sessions", json={"idempotency_key": "k1"}, headers=auth).json()
    assert a["session"]["id"] == b["session"]["id"]


def test_space_dashboard_and_delete(client, auth, ready_project):
    sid = ready_project["space"]["id"]
    dash = client.get(f"/spaces/{sid}", headers=auth).json()
    assert dash["project_count"] == 1 and dash["projects"][0]["materials"] == 1
    assert client.delete(f"/spaces/{sid}", headers=auth).status_code == 204
    assert client.get(f"/projects/{ready_project['project']['id']}", headers=auth).status_code == 404
    assert dbm.get_db()[dbm.CHUNKS].count_documents({}) == 0


def test_admin_views(client, auth, ready_project):
    from tests.conftest import register

    admin = register(client, "admin@example.com")
    ov = client.get("/admin/overview", headers=admin).json()
    assert ov["users"]["total"] == 2 and ov["materials"]["ready"] == 1
    users = client.get("/admin/users", headers=admin).json()
    learner = next(u for u in users if u["email"] == "learner@example.com")
    assert learner["projects"] == 1
    detail = client.get(f"/admin/users/{learner['id']}", headers=admin).json()
    assert detail["projects"][0]["materials"] == 1 and detail["timeline"]
    assert client.get("/admin/projects", headers=admin).json()[0]["owner"] == "learner@example.com"
    act = client.get("/admin/activity", params={"event_type": "material_processed"}, headers=admin).json()
    assert len(act) == 1
    ai = client.get("/admin/ai", headers=admin).json()
    assert ai["totals"]["requests"] >= 3 and any(f["feature"] == "concepts" for f in ai["by_feature"])
    health = client.get("/admin/health", headers=admin).json()
    assert health["database"]["ok"] and health["ai_providers"][0]["name"] == "fake"
    assert client.get("/admin/learning", headers=admin).status_code == 200
    assert client.get("/admin/prompts", headers=admin).json()[0]["version"]


def test_eval_run_and_regression_compare(client, auth, ready_project):
    from tests.conftest import register

    admin = register(client, "admin@example.com")
    pid = ready_project["project"]["id"]
    r = client.post("/admin/evals", json={"project_id": pid}, headers=admin)
    assert r.status_code == 201, r.text
    run = r.json()["run"]
    assert run["status"] == "completed" and run["total_cases"] >= 7
    assert run["scores"]["category:tutor_unsupported"] >= 0.7
    assert run["scores"]["category:safety"] >= 0.7
    assert run["prompt_versions"]["tutor"]
    r2 = client.post("/admin/evals", json={"project_id": pid}, headers=admin).json()["run"]
    assert r2["baseline_run_id"] == run["id"]
    assert client.get("/admin/evals", headers=admin).json()[0]["id"] == r2["id"]
    assert len(client.get(f"/admin/evals/{r2['id']}", headers=admin).json()["results"]) == r2["total_cases"]
